/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

//@type {import('@docusaurus/plugin-content-docs').SidebarsConfig} 

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    intentSidebar: {

        Overview: [
          "docs/Intent Recognition System/Overview/Objective",
          "docs/Intent Recognition System/Overview/Current State",
          "docs/Intent Recognition System/Overview/Future State",
                  ],

        System Design: [
          "docs/Intent Recognition System/System Design",
          ],

        Engineering: [
            "docs/Intent Recognition System/Engineering",
          ],

        Quality Assurance: [
            "docs/Intent Recognition System/Quality Assurance",
          ],

        Testing Procedures: [
            "docs/Intent Recognition System/Testing Procedures",
          ],

        Challenges and Solutions: [
            "docs/Intent Recognition System/Challenges and Solutions",
          ],

        References: [

            "docs/Intent Recognition System/References/Bibliography",
            "docs/Intent Recognition System/References/Frequently asked questions",
          ],

    },


    mseSidebar: {
    
        Overview: [
      "docs/MSE Assist/Overview/Objective",
      "docs/MSE Assist/Overview/Current State",
      "docs/MSE Assist/Overview/Future State",
                 ],


      System Design: [
        "docs/MSE Assist/System Design",
        "docs/MSE Assist/Changelog",
      ],

      Engineering: [
        "docs/MSE Assist/Engineering",
        "docs/MSE Assist/Engineering/Development",
        "docs/MSE Assist/Engineering/Evaluation",
      ],

      Operational Procedures: [
        "docs/MSE Assist/Operational Procedures",
      ],

      Challenges and Solutions: [
        "docs/MSE Assist/Challenges and Solutions",
      ],

      References: [

        "docs/MSE Assist/References" ,
        "docs/MSE Assist/References/Bibliography",
        "docs/MSE Assist/References/Frequently asked questions",
      ],

    },
  
};

export default sidebars;
