/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

//@type {import('@docusaurus/plugin-content-docs').SidebarsConfig}

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  intentSidebar: {
    Overview: [
      "Intent Recognition System/Overview/Objective",
      "Intent Recognition System/Overview/Current State",
      "Intent Recognition System/Overview/Future State",
    ],

    "System Design": ["Intent Recognition System/System Design"],
    // Engineering: [
    //   "MSE Assist/Engineering/Development",
    //   "MSE Assist/Engineering/Evaluation",
    //   "MSE Assist/Engineering/Deployment",
    // ],
    Engineering: [
      "Intent Recognition System/Engineering/Development",
      "Intent Recognition System/Engineering/Evaluation",

      "Intent Recognition System/Engineering/Deployment",
    ],

    "Testing Procedures": ["Intent Recognition System/Testing Procedures"],
    "Challenges and Solutions": [
      "Intent Recognition System/Challenges and Solutions",
    ],
    References: [
      "Intent Recognition System/References/Bibliography",
      "Intent Recognition System/References/Frequently asked questions",
    ],
  },

  mseSidebar: {
    Overview: [
      "MSE Assist/Overview/Objective",
      "MSE Assist/Overview/Current State",
      "MSE Assist/Overview/Desired State",
    ],
    "System Design": ["MSE Assist/System Design", "MSE Assist/Changelog"],
    Engineering: [
      "MSE Assist/Engineering/Development",
      "MSE Assist/Engineering/Evaluation",
      "MSE Assist/Engineering/Deployment",
    ],
    "Operational Procedures": ["MSE Assist/Operational Procedures"],
    "Challenges and Solutions": ["MSE Assist/Challenges and Solutions"],
    References: [
      "MSE Assist/References",
      "MSE Assist/References/Bibliography",
      "MSE Assist/References/Frequently asked questions",
    ],
  },
};

export default sidebars;
